version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: monitoring-mqtt
    ports:
      - "1883:1883"     # Default MQTT port
      - "9001:9001"     # MQTT WebSockets port
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: monitoring-web
    ports:
      - "80:80"         # HTTP Webserver port
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mosquitto
    restart: unless-stopped
